{"name": "test_get_json_failure", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'aiohttp.client_exceptions.ClientResponseError'>", "trace": "@pytest.mark.asyncio\n    async def test_get_json_failure():\n        url = \"https://jsonplaceholder.typicode.com/todos/invalid\"\n    \n        # Используем aioresponses для имитации запроса и генерации ошибки\n        with aioresponses() as mocked_responses:\n            mocked_responses.get(url, status=404)\n    \n            # Ожидаем, что при вызове get_json по данному URL возникнет ошибка ClientResponseError\n>           with pytest.raises(aiohttp.ClientResponseError) as exc_info:\nE           Failed: DID NOT RAISE <class 'aiohttp.client_exceptions.ClientResponseError'>\n\ntests\\test_app.py:16: Failed"}, "start": 1702545550801, "stop": 1702545550818, "uuid": "ad2701a1-d511-4549-beeb-6f21c7433806", "historyId": "4ae280fb04efa43257b4a1307274006f", "testCaseId": "4ae280fb04efa43257b4a1307274006f", "fullName": "tests.test_app#test_get_json_failure", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_app"}, {"name": "host", "value": "DESKTOP-RKLJ7AP"}, {"name": "thread", "value": "12980-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_app"}]}